### ISSUE TITLE
#7 Add Play and Stop Button to page with selected story

### ISSUE THREAD

**Issue by asnatschko** [asnatschko/capstone-project#16]
**Value Proposition**
As a reader I need to see a selected story on a single page with to buttons - Play and Stop for using them in the future.
**Description**

![image](https://user-images.githubusercontent.com/98124965/193048553-200940b8-f196-4055-b8e1-462b859f2e84.png)

**Acceptance Criteria**
 - [ ] when clicking on the story, a single page is opening.
 - [ ] the single page includes a play and a stop button

**Tasks**
 - [ ] Create a branch
 - [ ] create the logic for opening the story in a new page
 - [ ] create under the story text two buttons - Play and Stop
