### ISSUE TITLE
User story #1-draft

### ISSUE THREAD

**Issue by asnatschko** [asnatschko/capstone-project#2]
**Value Proposition**
As a reader I need to see several stories to be able to choose and read them
**Description**
 - [ ] Scribble / design or text
 
 
![user_story_#1](https://user-images.githubusercontent.com/98124965/190179876-1334120a-bd96-4a57-92fe-1b92c82f5c63.png)

**Acceptance Criteria**
 describe every scenario in detail
 e.g. All Inputs are required, show warning if empty.
 - [ ] when clicking on the r-button, the choosen story has to be shown
 - [ ] when clicking on the bookmark button, the choosen story has to be bookmarked (the bookmark icon has to be filled)

**Tasks**
(for developers team)
 list the tasks that need to be performed within the dev team
 e.g. Components, Storybook, testing
 - [ ] Create a branch
 - [ ] create a h1-Tag with "ReadMe"
 - [ ] create an unordered list with the stories as list elements
 - [ ] create a read-button 
 - [ ] create a bookmark button with toggle function

**Comment by MerleMak** [comment]
Hi Alex!
This User story seems a bit big to me.
How about for the first one you only display a story and one button which navigates you to the second story.
The overview of several stories would be the next user story and the bookmarks fucntionality would be a 3. userstory.

Babysteps :P
