### ISSUE TITLE
#12 Add upload button for typed story

### ISSUE THREAD

**Issue by asnatschko** [asnatschko/capstone-project#26]
**Value Proposition**
As a user I need to see after typing my story an upload button.
 
**Description**

![image](https://user-images.githubusercontent.com/98124965/194566746-ad64b3ee-7ef4-4196-b13c-877abf5ffaab.png)

**Acceptance Criteria**
 - [ ] when clicking on the save-button, the story is saved to all stories

**Tasks**
 - [ ] Create a branch
 - [ ] create the logic for the save-button
 - [ ] create the logic for the database
