### ISSUE TITLE
User story #1

### ISSUE THREAD

**Issue by asnatschko** [asnatschko/capstone-project#3]
**Value Proposition**
As a reader I need to see one story to be able to read it or switch to another story.
**Description**
 - [ ] Scribble / design or text
 
 
![UserStory_1](https://user-images.githubusercontent.com/98124965/190385508-19818a14-3519-4b65-930a-8baa3a97adca.png)

**Acceptance Criteria**
 describe every scenario in detail
 e.g. All Inputs are required, show warning if empty.
 - [ ] when clicking on the button "next story", the next story has to be shown

**Tasks**
(for developers team)
 list the tasks that need to be performed within the dev team
 e.g. Components, Storybook, testing
 - [ ] Create a branch
 - [ ] create a h1-Tag with "ReadMe"
 - [ ] create an unordered list with one story as list element
 - [ ] create a button "next story"
 - [ ] create an onClick-event for the button "next story" for showing next story

**Comment by asnatschko** [comment]
Thank you :)
