### ISSUE TITLE
User story #3

### ISSUE THREAD

**Issue by asnatschko** [asnatschko/capstone-project#5]
**Value Proposition**
As a reader I need to see several stories to be able to bookmark them
**Description**
 - [ ] Scribble / design or text
 
![UserStory_3](https://user-images.githubusercontent.com/98124965/190404146-4b1d9af4-ff53-46f0-ad86-174621e67a0b.png)

**Acceptance Criteria**
 describe every scenario in detail
 e.g. All Inputs are required, show warning if empty.
 - [ ] when clicking on the bookmark button, the choosen story has to be bookmarked (the bookmark icon has to be filled)

**Tasks**
(for developers team)
 list the tasks that need to be performed within the dev team
 e.g. Components, Storybook, testing
 - [ ] Create a branch
 - [ ] create a h1-Tag with "ReadMe"
 - [ ] create a bookmark button with toggle function
