### ISSUE TITLE
#4 - Adding a Nav-Bar with a Home-Button

### ISSUE THREAD

**Issue by asnatschko** [asnatschko/capstone-project#6]
**Value Proposition**
As a reader I need to have a fixed nav-bar with a home-button to be able to for the reader to get to the homepage.
**Description**
 
![UserStory4](https://user-images.githubusercontent.com/98124965/190619572-c8d5dcc2-eade-482f-9dad-d7d7696329c5.png)

**Acceptance Criteria**
 - [ ] when clicking on the home button, the homepage of the Readme-App shall be shown

**Tasks**
 - [ ] Create a branch
 - [ ] create a h1-Tag with "ReadMe"
 - [ ] create a fixed footer nav-Tag 
 - [ ] create a home-icon as a button in the nav-tag

**Comment by DoroVernier** [comment]
Very nice Alex!!!! 
One question: are you including any logic here?

**Comment by asnatschko** [comment]
Thank you=)
The logic will be in the next user story :)
