### ISSUE TITLE
#6 - Add two buttons in the nav-bar. Library and Settings

### ISSUE THREAD

**Issue by asnatschko** [asnatschko/capstone-project#8]
**Value Proposition**
As a reader I need to see a nav-bar with three icons Home, Library and Settings to be able to switch between them.
**Description**

![UserStory6](https://user-images.githubusercontent.com/98124965/190663868-406ddc6c-5df6-4f81-91aa-53c1813c178c.png)

**Acceptance Criteria**
 - [ ] when clicking on the library button, a library page shall be shown and the library - Icon shall be marked
 - [ ] when clicking on the settings button, a setting page shall be shown an the settings-icon shall be marked

**Tasks**
 - [ ] Create a branch
 - [ ] create the logic for a marked library icon and settings icon
 - [ ] create new empty pages Library and Settings

**Comment by K-Juno** [comment]
All clear! Good job!
